AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - ./**/*_spec.rb

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - ./**/*_spec.rb

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true
